spring:
  config:
    activate:
      on-profile: local

remote:
  agents:
    order-agent:
      url: http://localhost:9001
    delivery-agent:
      url: http://localhost:9002
    payment-agent:
      url: http://localhost:9003
