server:
  port: 9000

spring:
  ai:
    bedrock:
      aws:
        region: ${BEDROCK_REGION:ap-northeast-2}
      converse:
        chat:
          options:
            model: ${BEDROCK_MODEL_ID:}
    a2a:
      server:
        enabled: true

a2a:
  agent-url: ${AGENT_URL:}

remote:
  agents:
    delivery-agent:
      url: ${DELIVERY_AGENT_URL:}
    payment-agent:
      url: ${PAYMENT_AGENT_URL:}
