spring:
  config:
    activate:
      on-profile: local

server:
  port: 9001

a2a:
  agent-url: http://localhost:9001

remote:
  agents:
    delivery-agent:
      url: http://localhost:9002
    payment-agent:
      url: http://localhost:9003
